export type Sentiment = 'positive' | 'negative' | 'neutral';

export type LangCode =
  | 'en'
  | 'hi'
  | 'mr'
  | 'pa'
  | 'ta'
  | 'bn'
  | 'gu'
  | 'te'
  | 'kn'
  | 'ml'
  | 'ur'
  | (string & {});

export type ISODate = string;

export interface Article {
  id: string; // sha1(link), generated by backend
  title: string; // English (translated)
  summary: string;
  link: string;
  published: ISODate;
  category: string; // 'india' | 'politics' | 'hindi_bhaskar' | 'audio' ...
  language: LangCode;
  sentiment: Sentiment;
  sentimentScore: number; // 0..1 confidence/intensity
  reason: string;
  ministry: string | null;
  ministrySlug: string | null;
  keywords: string[];
  source?: string; // publisher or 'audio_upload'
  originalText?: string;
  translatedText?: string;
}

export interface SentimentCounts {
  positive: number;
  negative: number;
  neutral: number;
}

export interface OverviewKpis {
  totalArticles: number;
  totalArticlesDelta: number;
  netSentiment: number; // -100..100 = (pos - neg) / total * 100
  netSentimentDelta: number; // points vs previous period
  counts: SentimentCounts;
  criticalAlerts: number;
  languages: { language: LangCode; count: number; share: number }[];
  sparkline: { t: ISODate; total: number; net: number }[];
}

export interface TimeseriesPoint extends SentimentCounts {
  t: ISODate;
  net: number;
}

export interface DistributionRow extends SentimentCounts {
  key: string;
  label: string;
  total: number;
}

export interface MinistryStat {
  slug: string;
  name: string;
  mentions: number;
  sentimentIndex: number; // -100..100
  counts: SentimentCounts;
  negativeUrgency: number; // 0..100
  momentum: number; // 7d net change, points
  languageCoverage: number; // distinct languages / total tracked
  trend?: TimeseriesPoint[];
  topKeywords?: { term: string; weight: number; sentiment: Sentiment }[];
  schemes?: { name: string; mentions: number; sentimentIndex: number }[];
}

export type AlertSeverity = 'critical' | 'warning' | 'info';

export interface Alert {
  id: string;
  severity: AlertSeverity;
  ministrySlug: string;
  ministry: string;
  title: string;
  zScore: number;
  negativeCount24h: number;
  baselineNegative: number;
  topArticleIds: string[];
  raisedAt: ISODate;
}

export interface ChatSource {
  articleId: string;
  title: string;
  snippet: string;
  score: number; // similarity
  ministry: string | null;
  published: ISODate;
  link: string;
  sentiment: Sentiment;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  sources?: ChatSource[];
  status: 'streaming' | 'done' | 'error';
  createdAt: ISODate;
}

export interface ChatFilters {
  ministries?: string[];
  from?: ISODate;
  to?: ISODate;
  languages?: LangCode[];
}

export type AudioJobStatus =
  | 'uploaded'
  | 'transcribing'
  | 'translating'
  | 'analyzing'
  | 'ready'
  | 'indexed'
  | 'failed';

export interface TranscriptSegment {
  start: number;
  end: number;
  original: string;
  translated: string;
}

export interface AudioUpload {
  id: string;
  filename: string;
  durationSec: number | null;
  language: LangCode | null;
  status: AudioJobStatus;
  progress: number; // 0..1
  audioUrl: string;
  segments: TranscriptSegment[];
  preview: Pick<
    Article,
    'sentiment' | 'sentimentScore' | 'reason' | 'ministry' | 'keywords'
  > & { title?: string; summary?: string } | null;
  error?: string;
}

export interface Briefing {
  id: string;
  date: string; // YYYY-MM-DD
  headline: string;
  grievances: {
    ministry: string;
    summary: string;
    articleIds: string[];
    severity: AlertSeverity;
  }[];
  milestones: {
    ministry: string;
    summary: string;
    articleIds: string[];
  }[];
  netSentiment: number;
  generatedAt: ISODate;
  markdown: string;
}
